services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://192.168.222.141:8080 ### ici il faut mettre votre ip 
      - APP_KEY=base64:vP8S6p6pW9S6p6pW9S6p6pW9S6p6pW9S6p6pW9S6p6p=
      - DB_HOST=bookstack_db
      - DB_USER=bookstack 
      - DB_PASS=password_secret 
      - DB_DATABASE=bookstackapp
    volumes:
      - ./config:/config
    ports:
      - 8080:80
    restart: unless-stopped
    depends_on:
      - bookstack_db

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=password_admin
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=password_secret
    volumes:
      - ./db_data:/config
    restart: unless-stopped


##### Créer un dossier avec le fichier docker-compose.yml ci-dessus.

    Lancer le terminal dans ce dossier et taper : docker compose up -d.

Résultat : Ton wiki est accessible sur http://localhost:8080. Tu n'as plus qu'à créer quelques pages de "documentation fictive" (ex: "Procédure d'accès au Wi-Fi", "Annuaire du personnel")
